### ISSUE TITLE
Dbeaver driver folder location

### ISSUE THREAD

**Issue by aymaliev** [portapps/dbeaver-portable#1]
Hi
I am not aware if this is a bug, issue or a feature request, but:
"Can we have the .dbeaver-drivers folder within the app directory?"

Otherwise, dbeaver may be portable, but on every machine it will require downloading of drivers, and in the case of oracle, that is not straightforward.

**Comment by crazy-max** [comment]
Hi @aymaliev, it's more like a feature for me. From what I see there is a preference to change the driver path : https://github.com/dbeaver/dbeaver/blob/690b010e485ff7f6ee639e8929abb65bd3efc72c/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/ModelPreferences.java#L113

**Comment by aymaliev** [comment]
@crazy-max, one can change the path, but cannot make it relative. (At least I cannot make it relative)
Without relative paths, dbeaver is not very "portable" to me.
The very same logic applies to the workspace folder. Why bother change the location of the workspace folder if it is found in the {user} directory and one can change it from settings.

**Comment by crazy-max** [comment]
@aymaliev Don't worry I can make this change "on fly" while executing dbeaver-portable ;)

**Comment by crazy-max** [comment]
@aymaliev Should be ok in the latest release : https://portapps.github.io/app/dbeaver-portable/#download

**Comment by aymaliev** [comment]
Great. Tested and it works. 
I have also found a bunch of people requesting tthis feature on the official dbeaver forum. Hope they find it here.
Thank you.

Just an idea: 
In a similar way, you can add the eclipse "secure storage" folder to the data dir.

**Comment by crazy-max** [comment]
@aymaliev Share the link of Portapps on the forum if it can help people :)
