### ISSUE TITLE
Make the size of JRE smaller

### ISSUE THREAD

**Issue by lemon-juice** [portapps/dbeaver-portable#17]
I've just tried version 7.2.0 of DBeaver portable and it works great. However, I'm wondering why the `jre` folder is so large - after installation is takes up 115 MB of space. However, the size of `jre` folder in the standard DBeaver installation (`C:\Program Files\DBeaver\jre`) is only 44.3 MB. From a quick glance the file `jre\lib\modules` is the one that is much larger in your portable DBeaver than in standard DBeaver.

I did an experiment and deleted the `jre` folder in the portable installation and copied there the smaller `jre` from the desktop installation and DBeaver appears to work without any problems. Maybe the larger version of JRE is not necessary? This is a 70 MB saving in disk space, which is a lot. Could you bundle the smaller version of JRE in the portable installer?

**Comment by crazy-max** [comment]
@lemon-juice 

> Could you bundle the smaller version of JRE in the portable installer?

Sure LGTM

**Comment by lemon-juice** [comment]
Great, thanks!

**Comment by crazy-max** [comment]
@lemon-juice This is actually not feasable at this time cause the JRE is a pre-built one and is only available through the setup (which we could not extract properly). You can open an issue [on the official repo](https://github.com/dbeaver/dbeaver) to ask them to include the JRE in the zip archive too.

**Comment by lemon-juice** [comment]
Why is it not feasible? I can open the installer with 7-zip and extract the JRE without any problem. And AFAIK, the JRE does not change very often, for example all 7.x.x releases have the same JRE. Is it important that it is bundled in the official zip archive?

**Comment by crazy-max** [comment]
@lemon-juice I think we can do something. Keep you in touch.

**Comment by lemon-juice** [comment]
okay, thanks. If this is difficult to achieve for some reason then maybe an option in the installer would be handy to skip installation of JRE altogether, in which case the files to the jre folder would not be copied and the dbeaver jre settings would be left intact.

**Comment by crazy-max** [comment]
@lemon-juice Fixed with latest release.
